-- Crear tabla respuestas
CREATE TABLE respuestas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensaje TEXT NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    solucion BOOLEAN DEFAULT FALSE,
    topico_id BIGINT NOT NULL,
    autor_id BIGINT NOT NULL,
    CONSTRAINT fk_topico FOREIGN KEY (topico_id) REFERENCES topicos (id) ON DELETE CASCADE,
    CONSTRAINT fk_respuesta_autor FOREIGN KEY (autor_id) REFERENCES usuarios (id) ON DELETE CASCADE
);